export enum RequestError {
  CITY_ID_NOT_FOUND = 'city_id:not-found',
  BUILDING_CODE_NOT_FOUND = 'building_code:not-found',
  TECHNOLOGY_CODE_NOT_FOUND = 'technology_code:not-found',
  TROOP_CODE_NOT_FOUND = 'troop_code:not-found',
  TROOP_ID_NOT_FOUND = 'troop_id:not-found',
  OUTPOST_ID_NOT_FOUND = 'outpost_id:not-found',
  MOVEMENT_ID_NOT_FOUND = 'movement_id:not-found',
  QUEUE_ITEM_ID_NOT_FOUND = 'queue_item_id:not-found',
  REPORT_ID_NOT_FOUND = 'report_id:not-found',
  PLAYER_NAME_NOT_FOUND = 'player_name:not-found',
  CITY_NAME_NOT_FOUND = 'city_name:not-found',
  COUNT_NOT_FOUND = 'count:not-found',
  ORIGIN_NOT_FOUND = 'origin:not-found',
  DESTINATION_NOT_FOUND = 'destination:not-found',
  TROOPS_NOT_FOUND = 'troops:not-found',
  TROOP_CODES_NOT_FOUND = 'troop_codes:not-found',
  ACTION_NOT_FOUND = 'action:not-found',
  WAS_READ_NOT_FOUND = 'was_read:not-found',
  TOKEN_NOT_FOUND = 'token:not-found',
  PLAYER_ID_NOT_IN_CONTEXT = 'player_id:not-in-context',
}
