version: '3'
services:
  postgres:
    image: 'postgres:16'
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=eoneom
      - POSTGRES_PASSWORD=eoneom
      - POSTGRES_DB=eoneom
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
