/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharedRouteRouteImport } from './routes/_shared/route'
import { Route as SharedIndexRouteImport } from './routes/_shared/index'
import { Route as InboxReportRouteImport } from './routes/inbox/report'
import { Route as SharedReportRouteImport } from './routes/_shared/report'
import { Route as OutpostOutpostIdRouteRouteImport } from './routes/outpost/$outpostId/route'
import { Route as CityCityIdRouteRouteImport } from './routes/city/$cityId/route'
import { Route as OutpostOutpostIdIndexRouteImport } from './routes/outpost/$outpostId/index'
import { Route as CityCityIdIndexRouteImport } from './routes/city/$cityId/index'
import { Route as OutpostOutpostIdMapRouteImport } from './routes/outpost/$outpostId/map'
import { Route as CityCityIdTroopRouteImport } from './routes/city/$cityId/troop'
import { Route as CityCityIdTechnologyRouteImport } from './routes/city/$cityId/technology'
import { Route as CityCityIdMapRouteImport } from './routes/city/$cityId/map'
import { Route as CityCityIdBuildingRouteImport } from './routes/city/$cityId/building'
import { Route as OutpostOutpostIdMovementRouteRouteImport } from './routes/outpost/$outpostId/movement/route'
import { Route as CityCityIdMovementRouteRouteImport } from './routes/city/$cityId/movement/route'
import { Route as CityCityIdWorldIndexRouteImport } from './routes/city/$cityId/world/index'
import { Route as CityCityIdBaseIndexRouteImport } from './routes/city/$cityId/base/index'
import { Route as OutpostOutpostIdWorldMapRouteImport } from './routes/outpost/$outpostId/world/map'
import { Route as OutpostOutpostIdMovementMovementIdRouteImport } from './routes/outpost/$outpostId/movement/$movementId'
import { Route as CityCityIdWorldMapRouteImport } from './routes/city/$cityId/world/map'
import { Route as CityCityIdMovementMovementIdRouteImport } from './routes/city/$cityId/movement/$movementId'
import { Route as CityCityIdBaseTroopRouteImport } from './routes/city/$cityId/base/troop'
import { Route as CityCityIdBaseTechnologyRouteImport } from './routes/city/$cityId/base/technology'
import { Route as CityCityIdBaseBuildingRouteImport } from './routes/city/$cityId/base/building'
import { Route as OutpostOutpostIdWorldMovementRouteRouteImport } from './routes/outpost/$outpostId/world/movement/route'
import { Route as CityCityIdWorldMovementRouteRouteImport } from './routes/city/$cityId/world/movement/route'
import { Route as OutpostOutpostIdWorldMovementMovementIdRouteImport } from './routes/outpost/$outpostId/world/movement/$movementId'
import { Route as CityCityIdWorldMovementMovementIdRouteImport } from './routes/city/$cityId/world/movement/$movementId'

const SharedRouteRoute = SharedRouteRouteImport.update({
  id: '/_shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedRouteRoute,
} as any)
const InboxReportRoute = InboxReportRouteImport.update({
  id: '/inbox/report',
  path: '/inbox/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedReportRoute = SharedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SharedRouteRoute,
} as any)
const OutpostOutpostIdRouteRoute = OutpostOutpostIdRouteRouteImport.update({
  id: '/outpost/$outpostId',
  path: '/outpost/$outpostId',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityIdRouteRoute = CityCityIdRouteRouteImport.update({
  id: '/city/$cityId',
  path: '/city/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)
const OutpostOutpostIdIndexRoute = OutpostOutpostIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutpostOutpostIdRouteRoute,
} as any)
const CityCityIdIndexRoute = CityCityIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const OutpostOutpostIdMapRoute = OutpostOutpostIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => OutpostOutpostIdRouteRoute,
} as any)
const CityCityIdTroopRoute = CityCityIdTroopRouteImport.update({
  id: '/troop',
  path: '/troop',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdTechnologyRoute = CityCityIdTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdMapRoute = CityCityIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdBuildingRoute = CityCityIdBuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const OutpostOutpostIdMovementRouteRoute =
  OutpostOutpostIdMovementRouteRouteImport.update({
    id: '/movement',
    path: '/movement',
    getParentRoute: () => OutpostOutpostIdRouteRoute,
  } as any)
const CityCityIdMovementRouteRoute = CityCityIdMovementRouteRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdWorldIndexRoute = CityCityIdWorldIndexRouteImport.update({
  id: '/world/',
  path: '/world/',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdBaseIndexRoute = CityCityIdBaseIndexRouteImport.update({
  id: '/base/',
  path: '/base/',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const OutpostOutpostIdWorldMapRoute =
  OutpostOutpostIdWorldMapRouteImport.update({
    id: '/world/map',
    path: '/world/map',
    getParentRoute: () => OutpostOutpostIdRouteRoute,
  } as any)
const OutpostOutpostIdMovementMovementIdRoute =
  OutpostOutpostIdMovementMovementIdRouteImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => OutpostOutpostIdMovementRouteRoute,
  } as any)
const CityCityIdWorldMapRoute = CityCityIdWorldMapRouteImport.update({
  id: '/world/map',
  path: '/world/map',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdMovementMovementIdRoute =
  CityCityIdMovementMovementIdRouteImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => CityCityIdMovementRouteRoute,
  } as any)
const CityCityIdBaseTroopRoute = CityCityIdBaseTroopRouteImport.update({
  id: '/base/troop',
  path: '/base/troop',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdBaseTechnologyRoute =
  CityCityIdBaseTechnologyRouteImport.update({
    id: '/base/technology',
    path: '/base/technology',
    getParentRoute: () => CityCityIdRouteRoute,
  } as any)
const CityCityIdBaseBuildingRoute = CityCityIdBaseBuildingRouteImport.update({
  id: '/base/building',
  path: '/base/building',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const OutpostOutpostIdWorldMovementRouteRoute =
  OutpostOutpostIdWorldMovementRouteRouteImport.update({
    id: '/world/movement',
    path: '/world/movement',
    getParentRoute: () => OutpostOutpostIdRouteRoute,
  } as any)
const CityCityIdWorldMovementRouteRoute =
  CityCityIdWorldMovementRouteRouteImport.update({
    id: '/world/movement',
    path: '/world/movement',
    getParentRoute: () => CityCityIdRouteRoute,
  } as any)
const OutpostOutpostIdWorldMovementMovementIdRoute =
  OutpostOutpostIdWorldMovementMovementIdRouteImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => OutpostOutpostIdWorldMovementRouteRoute,
  } as any)
const CityCityIdWorldMovementMovementIdRoute =
  CityCityIdWorldMovementMovementIdRouteImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => CityCityIdWorldMovementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SharedIndexRoute
  '/city/$cityId': typeof CityCityIdRouteRouteWithChildren
  '/outpost/$outpostId': typeof OutpostOutpostIdRouteRouteWithChildren
  '/report': typeof SharedReportRoute
  '/inbox/report': typeof InboxReportRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId/': typeof CityCityIdIndexRoute
  '/outpost/$outpostId/': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/world/movement': typeof CityCityIdWorldMovementRouteRouteWithChildren
  '/outpost/$outpostId/world/movement': typeof OutpostOutpostIdWorldMovementRouteRouteWithChildren
  '/city/$cityId/base/building': typeof CityCityIdBaseBuildingRoute
  '/city/$cityId/base/technology': typeof CityCityIdBaseTechnologyRoute
  '/city/$cityId/base/troop': typeof CityCityIdBaseTroopRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/city/$cityId/world/map': typeof CityCityIdWorldMapRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
  '/outpost/$outpostId/world/map': typeof OutpostOutpostIdWorldMapRoute
  '/city/$cityId/base/': typeof CityCityIdBaseIndexRoute
  '/city/$cityId/world/': typeof CityCityIdWorldIndexRoute
  '/city/$cityId/world/movement/$movementId': typeof CityCityIdWorldMovementMovementIdRoute
  '/outpost/$outpostId/world/movement/$movementId': typeof OutpostOutpostIdWorldMovementMovementIdRoute
}
export interface FileRoutesByTo {
  '/report': typeof SharedReportRoute
  '/inbox/report': typeof InboxReportRoute
  '/': typeof SharedIndexRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId': typeof CityCityIdIndexRoute
  '/outpost/$outpostId': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/world/movement': typeof CityCityIdWorldMovementRouteRouteWithChildren
  '/outpost/$outpostId/world/movement': typeof OutpostOutpostIdWorldMovementRouteRouteWithChildren
  '/city/$cityId/base/building': typeof CityCityIdBaseBuildingRoute
  '/city/$cityId/base/technology': typeof CityCityIdBaseTechnologyRoute
  '/city/$cityId/base/troop': typeof CityCityIdBaseTroopRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/city/$cityId/world/map': typeof CityCityIdWorldMapRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
  '/outpost/$outpostId/world/map': typeof OutpostOutpostIdWorldMapRoute
  '/city/$cityId/base': typeof CityCityIdBaseIndexRoute
  '/city/$cityId/world': typeof CityCityIdWorldIndexRoute
  '/city/$cityId/world/movement/$movementId': typeof CityCityIdWorldMovementMovementIdRoute
  '/outpost/$outpostId/world/movement/$movementId': typeof OutpostOutpostIdWorldMovementMovementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shared': typeof SharedRouteRouteWithChildren
  '/city/$cityId': typeof CityCityIdRouteRouteWithChildren
  '/outpost/$outpostId': typeof OutpostOutpostIdRouteRouteWithChildren
  '/_shared/report': typeof SharedReportRoute
  '/inbox/report': typeof InboxReportRoute
  '/_shared/': typeof SharedIndexRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId/': typeof CityCityIdIndexRoute
  '/outpost/$outpostId/': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/world/movement': typeof CityCityIdWorldMovementRouteRouteWithChildren
  '/outpost/$outpostId/world/movement': typeof OutpostOutpostIdWorldMovementRouteRouteWithChildren
  '/city/$cityId/base/building': typeof CityCityIdBaseBuildingRoute
  '/city/$cityId/base/technology': typeof CityCityIdBaseTechnologyRoute
  '/city/$cityId/base/troop': typeof CityCityIdBaseTroopRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/city/$cityId/world/map': typeof CityCityIdWorldMapRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
  '/outpost/$outpostId/world/map': typeof OutpostOutpostIdWorldMapRoute
  '/city/$cityId/base/': typeof CityCityIdBaseIndexRoute
  '/city/$cityId/world/': typeof CityCityIdWorldIndexRoute
  '/city/$cityId/world/movement/$movementId': typeof CityCityIdWorldMovementMovementIdRoute
  '/outpost/$outpostId/world/movement/$movementId': typeof OutpostOutpostIdWorldMovementMovementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/report'
    | '/inbox/report'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId/'
    | '/outpost/$outpostId/'
    | '/city/$cityId/world/movement'
    | '/outpost/$outpostId/world/movement'
    | '/city/$cityId/base/building'
    | '/city/$cityId/base/technology'
    | '/city/$cityId/base/troop'
    | '/city/$cityId/movement/$movementId'
    | '/city/$cityId/world/map'
    | '/outpost/$outpostId/movement/$movementId'
    | '/outpost/$outpostId/world/map'
    | '/city/$cityId/base/'
    | '/city/$cityId/world/'
    | '/city/$cityId/world/movement/$movementId'
    | '/outpost/$outpostId/world/movement/$movementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/report'
    | '/inbox/report'
    | '/'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/city/$cityId/world/movement'
    | '/outpost/$outpostId/world/movement'
    | '/city/$cityId/base/building'
    | '/city/$cityId/base/technology'
    | '/city/$cityId/base/troop'
    | '/city/$cityId/movement/$movementId'
    | '/city/$cityId/world/map'
    | '/outpost/$outpostId/movement/$movementId'
    | '/outpost/$outpostId/world/map'
    | '/city/$cityId/base'
    | '/city/$cityId/world'
    | '/city/$cityId/world/movement/$movementId'
    | '/outpost/$outpostId/world/movement/$movementId'
  id:
    | '__root__'
    | '/_shared'
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/_shared/report'
    | '/inbox/report'
    | '/_shared/'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId/'
    | '/outpost/$outpostId/'
    | '/city/$cityId/world/movement'
    | '/outpost/$outpostId/world/movement'
    | '/city/$cityId/base/building'
    | '/city/$cityId/base/technology'
    | '/city/$cityId/base/troop'
    | '/city/$cityId/movement/$movementId'
    | '/city/$cityId/world/map'
    | '/outpost/$outpostId/movement/$movementId'
    | '/outpost/$outpostId/world/map'
    | '/city/$cityId/base/'
    | '/city/$cityId/world/'
    | '/city/$cityId/world/movement/$movementId'
    | '/outpost/$outpostId/world/movement/$movementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SharedRouteRoute: typeof SharedRouteRouteWithChildren
  CityCityIdRouteRoute: typeof CityCityIdRouteRouteWithChildren
  OutpostOutpostIdRouteRoute: typeof OutpostOutpostIdRouteRouteWithChildren
  InboxReportRoute: typeof InboxReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shared': {
      id: '/_shared'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SharedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shared/': {
      id: '/_shared/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof SharedRouteRoute
    }
    '/inbox/report': {
      id: '/inbox/report'
      path: '/inbox/report'
      fullPath: '/inbox/report'
      preLoaderRoute: typeof InboxReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shared/report': {
      id: '/_shared/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof SharedReportRouteImport
      parentRoute: typeof SharedRouteRoute
    }
    '/outpost/$outpostId': {
      id: '/outpost/$outpostId'
      path: '/outpost/$outpostId'
      fullPath: '/outpost/$outpostId'
      preLoaderRoute: typeof OutpostOutpostIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$cityId': {
      id: '/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/city/$cityId'
      preLoaderRoute: typeof CityCityIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outpost/$outpostId/': {
      id: '/outpost/$outpostId/'
      path: '/'
      fullPath: '/outpost/$outpostId/'
      preLoaderRoute: typeof OutpostOutpostIdIndexRouteImport
      parentRoute: typeof OutpostOutpostIdRouteRoute
    }
    '/city/$cityId/': {
      id: '/city/$cityId/'
      path: '/'
      fullPath: '/city/$cityId/'
      preLoaderRoute: typeof CityCityIdIndexRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/outpost/$outpostId/map': {
      id: '/outpost/$outpostId/map'
      path: '/map'
      fullPath: '/outpost/$outpostId/map'
      preLoaderRoute: typeof OutpostOutpostIdMapRouteImport
      parentRoute: typeof OutpostOutpostIdRouteRoute
    }
    '/city/$cityId/troop': {
      id: '/city/$cityId/troop'
      path: '/troop'
      fullPath: '/city/$cityId/troop'
      preLoaderRoute: typeof CityCityIdTroopRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/technology': {
      id: '/city/$cityId/technology'
      path: '/technology'
      fullPath: '/city/$cityId/technology'
      preLoaderRoute: typeof CityCityIdTechnologyRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/map': {
      id: '/city/$cityId/map'
      path: '/map'
      fullPath: '/city/$cityId/map'
      preLoaderRoute: typeof CityCityIdMapRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/building': {
      id: '/city/$cityId/building'
      path: '/building'
      fullPath: '/city/$cityId/building'
      preLoaderRoute: typeof CityCityIdBuildingRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/outpost/$outpostId/movement': {
      id: '/outpost/$outpostId/movement'
      path: '/movement'
      fullPath: '/outpost/$outpostId/movement'
      preLoaderRoute: typeof OutpostOutpostIdMovementRouteRouteImport
      parentRoute: typeof OutpostOutpostIdRouteRoute
    }
    '/city/$cityId/movement': {
      id: '/city/$cityId/movement'
      path: '/movement'
      fullPath: '/city/$cityId/movement'
      preLoaderRoute: typeof CityCityIdMovementRouteRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/world/': {
      id: '/city/$cityId/world/'
      path: '/world'
      fullPath: '/city/$cityId/world/'
      preLoaderRoute: typeof CityCityIdWorldIndexRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/base/': {
      id: '/city/$cityId/base/'
      path: '/base'
      fullPath: '/city/$cityId/base/'
      preLoaderRoute: typeof CityCityIdBaseIndexRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/outpost/$outpostId/world/map': {
      id: '/outpost/$outpostId/world/map'
      path: '/world/map'
      fullPath: '/outpost/$outpostId/world/map'
      preLoaderRoute: typeof OutpostOutpostIdWorldMapRouteImport
      parentRoute: typeof OutpostOutpostIdRouteRoute
    }
    '/outpost/$outpostId/movement/$movementId': {
      id: '/outpost/$outpostId/movement/$movementId'
      path: '/$movementId'
      fullPath: '/outpost/$outpostId/movement/$movementId'
      preLoaderRoute: typeof OutpostOutpostIdMovementMovementIdRouteImport
      parentRoute: typeof OutpostOutpostIdMovementRouteRoute
    }
    '/city/$cityId/world/map': {
      id: '/city/$cityId/world/map'
      path: '/world/map'
      fullPath: '/city/$cityId/world/map'
      preLoaderRoute: typeof CityCityIdWorldMapRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/movement/$movementId': {
      id: '/city/$cityId/movement/$movementId'
      path: '/$movementId'
      fullPath: '/city/$cityId/movement/$movementId'
      preLoaderRoute: typeof CityCityIdMovementMovementIdRouteImport
      parentRoute: typeof CityCityIdMovementRouteRoute
    }
    '/city/$cityId/base/troop': {
      id: '/city/$cityId/base/troop'
      path: '/base/troop'
      fullPath: '/city/$cityId/base/troop'
      preLoaderRoute: typeof CityCityIdBaseTroopRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/base/technology': {
      id: '/city/$cityId/base/technology'
      path: '/base/technology'
      fullPath: '/city/$cityId/base/technology'
      preLoaderRoute: typeof CityCityIdBaseTechnologyRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/base/building': {
      id: '/city/$cityId/base/building'
      path: '/base/building'
      fullPath: '/city/$cityId/base/building'
      preLoaderRoute: typeof CityCityIdBaseBuildingRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/outpost/$outpostId/world/movement': {
      id: '/outpost/$outpostId/world/movement'
      path: '/world/movement'
      fullPath: '/outpost/$outpostId/world/movement'
      preLoaderRoute: typeof OutpostOutpostIdWorldMovementRouteRouteImport
      parentRoute: typeof OutpostOutpostIdRouteRoute
    }
    '/city/$cityId/world/movement': {
      id: '/city/$cityId/world/movement'
      path: '/world/movement'
      fullPath: '/city/$cityId/world/movement'
      preLoaderRoute: typeof CityCityIdWorldMovementRouteRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/outpost/$outpostId/world/movement/$movementId': {
      id: '/outpost/$outpostId/world/movement/$movementId'
      path: '/$movementId'
      fullPath: '/outpost/$outpostId/world/movement/$movementId'
      preLoaderRoute: typeof OutpostOutpostIdWorldMovementMovementIdRouteImport
      parentRoute: typeof OutpostOutpostIdWorldMovementRouteRoute
    }
    '/city/$cityId/world/movement/$movementId': {
      id: '/city/$cityId/world/movement/$movementId'
      path: '/$movementId'
      fullPath: '/city/$cityId/world/movement/$movementId'
      preLoaderRoute: typeof CityCityIdWorldMovementMovementIdRouteImport
      parentRoute: typeof CityCityIdWorldMovementRouteRoute
    }
  }
}

interface SharedRouteRouteChildren {
  SharedReportRoute: typeof SharedReportRoute
  SharedIndexRoute: typeof SharedIndexRoute
}

const SharedRouteRouteChildren: SharedRouteRouteChildren = {
  SharedReportRoute: SharedReportRoute,
  SharedIndexRoute: SharedIndexRoute,
}

const SharedRouteRouteWithChildren = SharedRouteRoute._addFileChildren(
  SharedRouteRouteChildren,
)

interface CityCityIdMovementRouteRouteChildren {
  CityCityIdMovementMovementIdRoute: typeof CityCityIdMovementMovementIdRoute
}

const CityCityIdMovementRouteRouteChildren: CityCityIdMovementRouteRouteChildren =
  {
    CityCityIdMovementMovementIdRoute: CityCityIdMovementMovementIdRoute,
  }

const CityCityIdMovementRouteRouteWithChildren =
  CityCityIdMovementRouteRoute._addFileChildren(
    CityCityIdMovementRouteRouteChildren,
  )

interface CityCityIdWorldMovementRouteRouteChildren {
  CityCityIdWorldMovementMovementIdRoute: typeof CityCityIdWorldMovementMovementIdRoute
}

const CityCityIdWorldMovementRouteRouteChildren: CityCityIdWorldMovementRouteRouteChildren =
  {
    CityCityIdWorldMovementMovementIdRoute:
      CityCityIdWorldMovementMovementIdRoute,
  }

const CityCityIdWorldMovementRouteRouteWithChildren =
  CityCityIdWorldMovementRouteRoute._addFileChildren(
    CityCityIdWorldMovementRouteRouteChildren,
  )

interface CityCityIdRouteRouteChildren {
  CityCityIdMovementRouteRoute: typeof CityCityIdMovementRouteRouteWithChildren
  CityCityIdBuildingRoute: typeof CityCityIdBuildingRoute
  CityCityIdMapRoute: typeof CityCityIdMapRoute
  CityCityIdTechnologyRoute: typeof CityCityIdTechnologyRoute
  CityCityIdTroopRoute: typeof CityCityIdTroopRoute
  CityCityIdIndexRoute: typeof CityCityIdIndexRoute
  CityCityIdWorldMovementRouteRoute: typeof CityCityIdWorldMovementRouteRouteWithChildren
  CityCityIdBaseBuildingRoute: typeof CityCityIdBaseBuildingRoute
  CityCityIdBaseTechnologyRoute: typeof CityCityIdBaseTechnologyRoute
  CityCityIdBaseTroopRoute: typeof CityCityIdBaseTroopRoute
  CityCityIdWorldMapRoute: typeof CityCityIdWorldMapRoute
  CityCityIdBaseIndexRoute: typeof CityCityIdBaseIndexRoute
  CityCityIdWorldIndexRoute: typeof CityCityIdWorldIndexRoute
}

const CityCityIdRouteRouteChildren: CityCityIdRouteRouteChildren = {
  CityCityIdMovementRouteRoute: CityCityIdMovementRouteRouteWithChildren,
  CityCityIdBuildingRoute: CityCityIdBuildingRoute,
  CityCityIdMapRoute: CityCityIdMapRoute,
  CityCityIdTechnologyRoute: CityCityIdTechnologyRoute,
  CityCityIdTroopRoute: CityCityIdTroopRoute,
  CityCityIdIndexRoute: CityCityIdIndexRoute,
  CityCityIdWorldMovementRouteRoute:
    CityCityIdWorldMovementRouteRouteWithChildren,
  CityCityIdBaseBuildingRoute: CityCityIdBaseBuildingRoute,
  CityCityIdBaseTechnologyRoute: CityCityIdBaseTechnologyRoute,
  CityCityIdBaseTroopRoute: CityCityIdBaseTroopRoute,
  CityCityIdWorldMapRoute: CityCityIdWorldMapRoute,
  CityCityIdBaseIndexRoute: CityCityIdBaseIndexRoute,
  CityCityIdWorldIndexRoute: CityCityIdWorldIndexRoute,
}

const CityCityIdRouteRouteWithChildren = CityCityIdRouteRoute._addFileChildren(
  CityCityIdRouteRouteChildren,
)

interface OutpostOutpostIdMovementRouteRouteChildren {
  OutpostOutpostIdMovementMovementIdRoute: typeof OutpostOutpostIdMovementMovementIdRoute
}

const OutpostOutpostIdMovementRouteRouteChildren: OutpostOutpostIdMovementRouteRouteChildren =
  {
    OutpostOutpostIdMovementMovementIdRoute:
      OutpostOutpostIdMovementMovementIdRoute,
  }

const OutpostOutpostIdMovementRouteRouteWithChildren =
  OutpostOutpostIdMovementRouteRoute._addFileChildren(
    OutpostOutpostIdMovementRouteRouteChildren,
  )

interface OutpostOutpostIdWorldMovementRouteRouteChildren {
  OutpostOutpostIdWorldMovementMovementIdRoute: typeof OutpostOutpostIdWorldMovementMovementIdRoute
}

const OutpostOutpostIdWorldMovementRouteRouteChildren: OutpostOutpostIdWorldMovementRouteRouteChildren =
  {
    OutpostOutpostIdWorldMovementMovementIdRoute:
      OutpostOutpostIdWorldMovementMovementIdRoute,
  }

const OutpostOutpostIdWorldMovementRouteRouteWithChildren =
  OutpostOutpostIdWorldMovementRouteRoute._addFileChildren(
    OutpostOutpostIdWorldMovementRouteRouteChildren,
  )

interface OutpostOutpostIdRouteRouteChildren {
  OutpostOutpostIdMovementRouteRoute: typeof OutpostOutpostIdMovementRouteRouteWithChildren
  OutpostOutpostIdMapRoute: typeof OutpostOutpostIdMapRoute
  OutpostOutpostIdIndexRoute: typeof OutpostOutpostIdIndexRoute
  OutpostOutpostIdWorldMovementRouteRoute: typeof OutpostOutpostIdWorldMovementRouteRouteWithChildren
  OutpostOutpostIdWorldMapRoute: typeof OutpostOutpostIdWorldMapRoute
}

const OutpostOutpostIdRouteRouteChildren: OutpostOutpostIdRouteRouteChildren = {
  OutpostOutpostIdMovementRouteRoute:
    OutpostOutpostIdMovementRouteRouteWithChildren,
  OutpostOutpostIdMapRoute: OutpostOutpostIdMapRoute,
  OutpostOutpostIdIndexRoute: OutpostOutpostIdIndexRoute,
  OutpostOutpostIdWorldMovementRouteRoute:
    OutpostOutpostIdWorldMovementRouteRouteWithChildren,
  OutpostOutpostIdWorldMapRoute: OutpostOutpostIdWorldMapRoute,
}

const OutpostOutpostIdRouteRouteWithChildren =
  OutpostOutpostIdRouteRoute._addFileChildren(
    OutpostOutpostIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SharedRouteRoute: SharedRouteRouteWithChildren,
  CityCityIdRouteRoute: CityCityIdRouteRouteWithChildren,
  OutpostOutpostIdRouteRoute: OutpostOutpostIdRouteRouteWithChildren,
  InboxReportRoute: InboxReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
