/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Auth {
  id: Generated<string>;
  last_action_at: Timestamp;
  player_id: string;
  token: string;
}

export interface Building {
  city_id: string;
  code: string;
  id: Generated<string>;
  level: number;
}

export interface BuildingUpgradeQueue {
  building_code: string;
  city_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
}

export interface Cell {
  city_id: string | null;
  id: Generated<string>;
  mushroom_coefficient: number;
  plastic_coefficient: number;
  sector: number;
  solar_coefficient: number;
  type: string;
  x: number;
  y: number;
}

export interface City {
  id: Generated<string>;
  name: string;
  player_id: string;
}

export interface Exploration {
  id: Generated<string>;
  player_id: string;
}

export interface ExplorationCell {
  cell_id: string;
  exploration_id: string;
}

export interface Movement {
  action: string;
  destination_sector: number;
  destination_x: number;
  destination_y: number;
  id: Generated<string>;
  mushroom: number;
  origin_sector: number;
  origin_x: number;
  origin_y: number;
  plastic: number;
  player_id: string;
}

export interface Outpost {
  cell_id: string;
  id: Generated<string>;
  player_id: string;
  type: string;
}

export interface Player {
  id: Generated<string>;
  name: string;
}

export interface Report {
  destination_sector: number;
  destination_x: number;
  destination_y: number;
  id: Generated<string>;
  mushroom: Generated<number>;
  origin_sector: number;
  origin_x: number;
  origin_y: number;
  plastic: Generated<number>;
  player_id: string;
  recorded_at: Timestamp;
  remaining_mushroom: Generated<number>;
  remaining_plastic: Generated<number>;
  type: string;
  was_read: Generated<boolean>;
}

export interface ReportTroop {
  code: string;
  count: number;
  id: Generated<string>;
  report_id: string;
}

export interface ResourceStock {
  cell_id: string;
  id: Generated<string>;
  last_mushroom_gather: Timestamp;
  last_plastic_gather: Timestamp;
  mushroom: number;
  plastic: number;
}

export interface Technology {
  code: string;
  id: Generated<string>;
  level: number;
  player_id: string;
}

export interface Troop {
  cell_id: string | null;
  code: string;
  count: Generated<number>;
  id: Generated<string>;
  movement_id: string | null;
  player_id: string;
}

export interface DB {
  auth: Auth;
  building: Building;
  building_upgrade_queue: BuildingUpgradeQueue;
  cell: Cell;
  city: City;
  exploration: Exploration;
  exploration_cell: ExplorationCell;
  movement: Movement;
  outpost: Outpost;
  player: Player;
  report: Report;
  report_troop: ReportTroop;
  resource_stock: ResourceStock;
  technology: Technology;
  troop: Troop;
}
